CREATE TABLE IF NOT EXISTS customers (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(180) NOT NULL,
  document VARCHAR(20) NULL,
  phone VARCHAR(30) NULL,
  whatsapp VARCHAR(30) NULL,
  email VARCHAR(190) NULL,
  birth_date DATE NULL,
  postal_code VARCHAR(12) NULL,
  street VARCHAR(180) NULL,
  street_number VARCHAR(30) NULL,
  address_complement VARCHAR(100) NULL,
  neighborhood VARCHAR(120) NULL,
  city VARCHAR(120) NULL,
  state CHAR(2) NULL,
  notes TEXT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_customers_document (document),
  KEY idx_customers_name (name),
  KEY idx_customers_phone (phone)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS suppliers (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  legal_name VARCHAR(180) NOT NULL,
  trade_name VARCHAR(180) NULL,
  document VARCHAR(20) NULL,
  contact_name VARCHAR(150) NULL,
  phone VARCHAR(30) NULL,
  whatsapp VARCHAR(30) NULL,
  email VARCHAR(190) NULL,
  postal_code VARCHAR(12) NULL,
  street VARCHAR(180) NULL,
  street_number VARCHAR(30) NULL,
  address_complement VARCHAR(100) NULL,
  neighborhood VARCHAR(120) NULL,
  city VARCHAR(120) NULL,
  state CHAR(2) NULL,
  notes TEXT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_suppliers_document (document),
  KEY idx_suppliers_legal_name (legal_name),
  KEY idx_suppliers_trade_name (trade_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS purchases (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  supplier_id BIGINT UNSIGNED NOT NULL,
  created_by_user_id BIGINT UNSIGNED NOT NULL,
  cancelled_by_user_id BIGINT UNSIGNED NULL,
  document_number VARCHAR(100) NULL,
  status ENUM('DRAFT', 'ORDERED', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED') NOT NULL DEFAULT 'DRAFT',
  purchase_date DATE NOT NULL,
  expected_date DATE NULL,
  received_at DATETIME(3) NULL,
  subtotal DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  discount_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  freight_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  other_expenses_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  total_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  notes TEXT NULL,
  cancelled_at DATETIME(3) NULL,
  cancellation_reason VARCHAR(500) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_purchases_supplier_document (supplier_id, document_number),
  KEY idx_purchases_status_date (status, purchase_date),
  KEY idx_purchases_created_by (created_by_user_id),
  CONSTRAINT chk_purchases_subtotal CHECK (subtotal >= 0),
  CONSTRAINT chk_purchases_discount CHECK (discount_amount >= 0),
  CONSTRAINT chk_purchases_freight CHECK (freight_amount >= 0),
  CONSTRAINT chk_purchases_other_expenses CHECK (other_expenses_amount >= 0),
  CONSTRAINT chk_purchases_total CHECK (total_amount >= 0),
  CONSTRAINT fk_purchases_supplier
    FOREIGN KEY (supplier_id) REFERENCES suppliers (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_purchases_created_by
    FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_purchases_cancelled_by
    FOREIGN KEY (cancelled_by_user_id) REFERENCES users (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS purchase_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  purchase_id BIGINT UNSIGNED NOT NULL,
  product_sku_id BIGINT UNSIGNED NOT NULL,
  description_snapshot VARCHAR(255) NOT NULL,
  sku_snapshot VARCHAR(100) NOT NULL,
  quantity_ordered INT UNSIGNED NOT NULL,
  quantity_received INT UNSIGNED NOT NULL DEFAULT 0,
  unit_cost DECIMAL(15,2) NOT NULL,
  discount_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  line_total DECIMAL(15,2) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_purchase_items_purchase (purchase_id),
  KEY idx_purchase_items_sku (product_sku_id),
  CONSTRAINT chk_purchase_items_quantity CHECK (quantity_ordered > 0),
  CONSTRAINT chk_purchase_items_received CHECK (quantity_received <= quantity_ordered),
  CONSTRAINT chk_purchase_items_unit_cost CHECK (unit_cost >= 0),
  CONSTRAINT chk_purchase_items_discount CHECK (discount_amount >= 0),
  CONSTRAINT chk_purchase_items_total CHECK (line_total >= 0),
  CONSTRAINT fk_purchase_items_purchase
    FOREIGN KEY (purchase_id) REFERENCES purchases (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_purchase_items_sku
    FOREIGN KEY (product_sku_id) REFERENCES product_skus (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sales (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  sale_number VARCHAR(50) NOT NULL,
  seller_user_id BIGINT UNSIGNED NOT NULL,
  customer_id BIGINT UNSIGNED NULL,
  cancelled_by_user_id BIGINT UNSIGNED NULL,
  status ENUM('DRAFT', 'COMPLETED', 'CANCELLED', 'PARTIALLY_RETURNED', 'RETURNED') NOT NULL DEFAULT 'DRAFT',
  subtotal DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  discount_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  surcharge_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  total_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  notes TEXT NULL,
  sold_at DATETIME(3) NULL,
  cancelled_at DATETIME(3) NULL,
  cancellation_reason VARCHAR(500) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_sales_sale_number (sale_number),
  KEY idx_sales_status_sold_at (status, sold_at),
  KEY idx_sales_seller_sold_at (seller_user_id, sold_at),
  KEY idx_sales_customer_sold_at (customer_id, sold_at),
  CONSTRAINT chk_sales_subtotal CHECK (subtotal >= 0),
  CONSTRAINT chk_sales_discount CHECK (discount_amount >= 0),
  CONSTRAINT chk_sales_surcharge CHECK (surcharge_amount >= 0),
  CONSTRAINT chk_sales_total CHECK (total_amount >= 0),
  CONSTRAINT fk_sales_seller
    FOREIGN KEY (seller_user_id) REFERENCES users (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_sales_customer
    FOREIGN KEY (customer_id) REFERENCES customers (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_sales_cancelled_by
    FOREIGN KEY (cancelled_by_user_id) REFERENCES users (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sale_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  sale_id BIGINT UNSIGNED NOT NULL,
  product_sku_id BIGINT UNSIGNED NOT NULL,
  product_name_snapshot VARCHAR(180) NOT NULL,
  sku_snapshot VARCHAR(100) NOT NULL,
  variant_snapshot VARCHAR(180) NULL,
  quantity INT UNSIGNED NOT NULL,
  original_unit_price DECIMAL(15,2) NOT NULL,
  discount_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  effective_unit_price DECIMAL(15,2) NOT NULL,
  line_total DECIMAL(15,2) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_sale_items_sale (sale_id),
  KEY idx_sale_items_sku (product_sku_id),
  CONSTRAINT chk_sale_items_quantity CHECK (quantity > 0),
  CONSTRAINT chk_sale_items_original_price CHECK (original_unit_price >= 0),
  CONSTRAINT chk_sale_items_discount CHECK (discount_amount >= 0),
  CONSTRAINT chk_sale_items_effective_price CHECK (effective_unit_price >= 0),
  CONSTRAINT chk_sale_items_total CHECK (line_total >= 0),
  CONSTRAINT fk_sale_items_sale
    FOREIGN KEY (sale_id) REFERENCES sales (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_sale_items_sku
    FOREIGN KEY (product_sku_id) REFERENCES product_skus (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
