'use strict';
const express = require('express');
const controller = require('../controllers/financeController');
const { authenticate } = require('../middlewares/authenticate');
const { authorize } = require('../middlewares/authorize');
const { guardDisbursementReversal, guardPayableSettlement, guardReceiptReversal, guardReceivableSettlement } = require('../middlewares/financeIdempotencyGuard');
const router = express.Router();
router.use(authenticate);
router.get('/summary', authorize('finance.read'), controller.summary);
router.get('/flow', authorize('finance.read'), controller.flow);
router.get('/categories', authorize('finance.read'), controller.categories);
router.post('/categories', authorize('finance.manage'), controller.createCategory);
router.patch('/categories/:id', authorize('finance.manage'), controller.updateCategory);
router.get('/receivables', authorize('finance.read'), controller.receivables);
router.post('/receivables', authorize('finance.manage'), controller.createReceivable);
router.post('/receivables/:id/receive', authorize('finance.manage'), guardReceivableSettlement, controller.receiveReceivable);
router.post('/receivables/:id/cancel', authorize('finance.manage'), controller.cancelReceivable);
router.get('/payables', authorize('finance.read'), controller.payables);
router.post('/payables', authorize('finance.manage'), controller.createPayable);
router.post('/payables/:id/pay', authorize('finance.manage'), guardPayableSettlement, controller.payPayable);
router.post('/payables/:id/cancel', authorize('finance.manage'), controller.cancelPayable);
router.get('/transactions', authorize('finance.read'), controller.transactions);
router.post('/receipts/:id/reverse', authorize('finance.manage'), guardReceiptReversal, controller.reverseReceipt);
router.post('/disbursements/:id/reverse', authorize('finance.manage'), guardDisbursementReversal, controller.reverseDisbursement);
router.get('/purchases/pending', authorize('finance.read'), controller.pendingPurchases);
router.post('/purchases/:id/financialize', authorize('finance.manage'), controller.financializePurchase);
module.exports = router;
