'use strict';
const express=require('express');
const controller=require('../controllers/publicCatalogController');
const{catalogRateLimit}=require('../middlewares/catalogRateLimit');
const router=express.Router();
router.use(catalogRateLimit);
router.get('/meta',controller.metadata);
router.get('/products',controller.products);
router.get('/products/:id',controller.product);
module.exports=router;
