'use strict';
const express=require('express');
const controller=require('../controllers/purchaseController');
const {authenticate}=require('../middlewares/authenticate');
const {authorize}=require('../middlewares/authorize');
const router=express.Router();
router.use(authenticate);
router.get('/meta/skus',authorize('purchases.read'),controller.lookupSkus);
router.get('/',authorize('purchases.read'),controller.list);
router.get('/:id',authorize('purchases.read'),controller.getById);
router.post('/',authorize('purchases.manage'),controller.create);
router.patch('/:id',authorize('purchases.manage'),controller.update);
router.post('/:id/items',authorize('purchases.manage'),controller.addItem);
router.patch('/:id/items/:itemId',authorize('purchases.manage'),controller.updateItem);
router.post('/:id/items/:itemId/cancel',authorize('purchases.manage'),controller.cancelItem);
router.post('/:id/order',authorize('purchases.manage'),controller.order);
router.post('/:id/cancel',authorize('purchases.manage'),controller.cancel);
router.post('/:id/receipts',authorize('purchases.receive'),controller.receive);
module.exports=router;
