'use strict';
const express=require('express');
const controller=require('../controllers/saleController');
const {authenticate}=require('../middlewares/authenticate');
const {authorize}=require('../middlewares/authorize');
const {protectCatalogConvertedSaleItems}=require('../middlewares/catalogConvertedSaleGuard');
const router=express.Router();
router.use(authenticate);
router.get('/meta/skus',authorize('sales.read'),controller.lookupSkus);
router.get('/',authorize('sales.read'),controller.list);
router.get('/:id',authorize('sales.read'),controller.getById);
router.post('/',authorize('sales.create'),controller.create);
router.patch('/:id',authorize('sales.create'),controller.update);
router.post('/:id/items',authorize('sales.create'),protectCatalogConvertedSaleItems,controller.addItem);
router.patch('/:id/items/:itemId',authorize('sales.create'),protectCatalogConvertedSaleItems,controller.updateItem);
router.post('/:id/items/:itemId/cancel',authorize('sales.create'),protectCatalogConvertedSaleItems,controller.cancelItem);
router.patch('/:id/pricing',authorize('sales.discount'),controller.pricing);
router.patch('/:id/items/:itemId/discount',authorize('sales.discount'),controller.itemDiscount);
router.post('/:id/finalize',authorize('sales.create'),controller.finalize);
router.post('/:id/cancel',authorize('sales.cancel'),controller.cancel);
module.exports=router;
