'use strict';

const { getPool } = require('../config/database');
const supplierRepository = require('../repositories/supplierRepository');
const { createAuditLog } = require('../repositories/auditRepository');
const { HttpError } = require('../utils/httpError');
const { maskDocument, normalizeSupplierInput, parseBoolean, parsePagination } = require('../utils/supplierValidation');
function parseId(value){const id=Number(value);if(!Number.isSafeInteger(id)||id<1)throw new HttpError(400,'INVALID_SUPPLIER_ID','Fornecedor inválido.');return id;}
function parseOptionalBoolean(value){if(value===undefined||value===null||value==='')return null;return parseBoolean(value,'Status');}
function sanitizeSearch(value){return String(value??'').trim().slice(0,190);}function digits(value){return String(value??'').replace(/\D/g,'');}
function listView(row){const {document,...rest}=row;return {...rest,document_masked:maskDocument(document)};}
function auditFields(data){return {fields:Object.keys(data).sort(),...(Object.prototype.hasOwnProperty.call(data,'isActive')?{isActive:data.isActive}:{})};}
async function listSuppliers(query={}){const pagination=parsePagination(query);const q=sanitizeSearch(query.q);const result=await supplierRepository.listSuppliers({q,numericQ:digits(q),isActive:parseOptionalBoolean(query.isActive)},pagination);return {data:result.rows.map(listView),pagination:{page:pagination.page,pageSize:pagination.pageSize,total:result.total,totalPages:Math.max(1,Math.ceil(result.total/pagination.pageSize))}};}
async function lookupSuppliers(query={}){const q=sanitizeSearch(query.q);if(q.length<2)throw new HttpError(400,'SEARCH_TOO_SHORT','Informe pelo menos 2 caracteres para buscar fornecedor.');return (await supplierRepository.lookupSuppliers(q,digits(q))).map(listView);}
async function getSupplier(supplierId){const supplier=await supplierRepository.findSupplierById(parseId(supplierId));if(!supplier)throw new HttpError(404,'SUPPLIER_NOT_FOUND','Fornecedor não encontrado.');return supplier;}
async function createSupplier(input,actor){const data=normalizeSupplierInput(input);const connection=await getPool().getConnection();try{await connection.beginTransaction();const id=await supplierRepository.createSupplier(data,actor.id,connection);await createAuditLog({userId:actor.id,actionCode:'SUPPLIER_CREATED',entityType:'SUPPLIER',entityId:id,newData:auditFields(data)},connection);await connection.commit();return id;}catch(error){await connection.rollback();if(error.code==='ER_DUP_ENTRY')throw new HttpError(409,'SUPPLIER_DOCUMENT_EXISTS','Já existe fornecedor com este CPF/CNPJ.');throw error;}finally{connection.release();}}
async function updateSupplier(supplierId,input,actor){const id=parseId(supplierId);const changes=normalizeSupplierInput(input,{partial:true});if(!Object.keys(changes).length)throw new HttpError(400,'NO_CHANGES','Nenhuma alteração válida foi informada.');const connection=await getPool().getConnection();try{await connection.beginTransaction();const current=await supplierRepository.findSupplierForUpdate(id,connection);if(!current)throw new HttpError(404,'SUPPLIER_NOT_FOUND','Fornecedor não encontrado.');if(changes.isActive===false&&current.is_active){const openPurchases=await supplierRepository.countOpenPurchases(id,connection);if(openPurchases>0)throw new HttpError(409,'SUPPLIER_HAS_OPEN_PURCHASES','Fornecedor possui compras em aberto e não pode ser inativado.');}await supplierRepository.updateSupplier(id,changes,actor.id,connection);await createAuditLog({userId:actor.id,actionCode:'SUPPLIER_UPDATED',entityType:'SUPPLIER',entityId:id,previousData:{isActive:Boolean(current.is_active)},newData:auditFields(changes)},connection);await connection.commit();}catch(error){await connection.rollback();if(error.code==='ER_DUP_ENTRY')throw new HttpError(409,'SUPPLIER_DOCUMENT_EXISTS','Já existe fornecedor com este CPF/CNPJ.');throw error;}finally{connection.release();}}
module.exports={createSupplier,getSupplier,listSuppliers,lookupSuppliers,updateSupplier};
