'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const{groupVariants,mapCard,money,moneyToCents,priceRangeFromRows,publicImageUrl}=require('../src/utils/publicCatalogMapper');
test('normaliza dinheiro sem usar float de apresentação',()=>{assert.equal(money('149.9'),'149.90');assert.equal(moneyToCents('149.90'),14990);});
test('aceita somente caminho público de mídia de produto',()=>{assert.equal(publicImageUrl('/media/products/a-1.webp'),'/media/products/a-1.webp');assert.equal(publicImageUrl('/etc/passwd'),null);assert.equal(publicImageUrl('/media/products/../secret'),null);});
test('card público não contém campos administrativos',()=>{const card=mapCard({id:1,name:'Tênis',model:'X',audience:'Unissex',collection_name:null,material:'Couro',is_featured:1,category_name:'Tênis',category_slug:'tenis',brand_name:'NM',brand_slug:'nm',primary_image:'/media/products/a.webp',price_from:'100.00',price_to:'120.00',has_stock:1,base_cost_price:'50.00',internal_code:'SECRET'});assert.equal(card.name,'Tênis');assert.equal(Object.hasOwn(card,'internal_code'),false);assert.equal(Object.hasOwn(card,'base_cost_price'),false);});
test('agrupa tamanhos por variante e sinaliza promoção',()=>{const v=groupVariants([{variant_id:2,variant_name:null,color_name:'Preto',hex_code:'#000000',sku_id:10,size_id:1,size_label:'38',regular_price:'150.00',current_price:'129.90',is_available:1},{variant_id:2,variant_name:null,color_name:'Preto',hex_code:'#000000',sku_id:11,size_id:2,size_label:'39',regular_price:'150.00',current_price:'150.00',is_available:0}]);assert.equal(v.length,1);assert.equal(v[0].sizes.length,2);assert.equal(v[0].sizes[0].price.onSale,true);assert.equal(v[0].sizes[1].available,false);});
test('faixa de preço usa centavos exatos',()=>{assert.deepEqual(priceRangeFromRows([{current_price:'99.90'},{current_price:'100.01'}],'150.00'),{from:'99.90',to:'100.01'});});
test('faixa de preço usa preço base quando não há grade',()=>assert.deepEqual(priceRangeFromRows([],'179.90'),{from:'179.90',to:'179.90'}));
