'use strict';
const { getPool } = require('../config/database');
function db(connection){return connection||getPool();}
async function findPublicSkuForOrder(id,connection){const[rows]=await connection.execute(`SELECT ps.id,ps.sku,p.id product_id,p.name product_name,p.is_active product_is_active,p.is_catalog_visible,p.base_sale_price,p.promotional_price,pv.id variant_id,pv.is_active variant_is_active,c.name color_name,c.is_active color_is_active,sz.label size_label,sz.is_active size_is_active,ps.is_active sku_is_active,COALESCE(ps.promotional_price,ps.sale_price,p.promotional_price,p.base_sale_price) current_price FROM product_skus ps JOIN product_variants pv ON pv.id=ps.product_variant_id JOIN products p ON p.id=pv.product_id JOIN colors c ON c.id=pv.color_id JOIN sizes sz ON sz.id=ps.size_id WHERE ps.id=? LIMIT 1`,[id]);return rows[0]||null;}
async function ensureBalance(skuId,connection){await connection.execute('INSERT IGNORE INTO stock_balances(product_sku_id,quantity) VALUES(?,0)',[skuId]);}
async function lockBalance(skuId,connection){const[rows]=await connection.execute('SELECT product_sku_id,quantity FROM stock_balances WHERE product_sku_id=? FOR UPDATE',[skuId]);return rows[0]||null;}
async function expireAll(){const pool=getPool();await pool.query("UPDATE stock_reservations SET status='EXPIRED' WHERE status='ACTIVE' AND expires_at IS NOT NULL AND expires_at<=CURRENT_TIMESTAMP(3)");await pool.query("UPDATE catalog_orders SET status='EXPIRED' WHERE status='CONFIRMED' AND reservation_expires_at IS NOT NULL AND reservation_expires_at<=CURRENT_TIMESTAMP(3)");}
async function findByPublicOperationKey(key,connection=null){const[rows]=await db(connection).execute('SELECT * FROM catalog_orders WHERE public_operation_key=? LIMIT 1',[key]);return rows[0]||null;}
async function createOrder(data,connection){const[r]=await connection.execute(`INSERT INTO catalog_orders(order_number,customer_id,assigned_user_id,converted_sale_id,status,contact_name,contact_phone,contact_whatsapp,contact_email,public_token_hash,public_operation_key,request_hash,subtotal,total_amount,notes) VALUES(?,NULL,NULL,NULL,'NEW',?,?,?,?,?,?,?,0.00,0.00,?)`,[data.temporaryNumber,data.contactName,data.contactPhone,data.contactWhatsapp,data.contactEmail,data.publicTokenHash,data.operationKey,data.requestHash,data.notes]);return r.insertId;}
async function setOrderNumber(id,number,connection){await connection.execute('UPDATE catalog_orders SET order_number=? WHERE id=?',[number,id]);}
async function createItem(orderId,data,connection){const[r]=await connection.execute(`INSERT INTO catalog_order_items(catalog_order_id,product_sku_id,product_name_snapshot,sku_snapshot,variant_snapshot,quantity,unit_price,line_total) VALUES(?,?,?,?,?,?,?,?)`,[orderId,data.skuId,data.productName,data.skuSnapshot,data.variantSnapshot,data.quantity,data.unitPrice,data.lineTotal]);return r.insertId;}
async function setTotals(id,subtotal,total,connection){await connection.execute('UPDATE catalog_orders SET subtotal=?,total_amount=? WHERE id=?',[subtotal,total,id]);}
async function findPublicTracking(number,tokenHash,connection=null){const[rows]=await db(connection).execute(`SELECT id,order_number,status,total_amount,created_at,updated_at,reservation_expires_at,converted_sale_id FROM catalog_orders WHERE order_number=? AND public_token_hash=? LIMIT 1`,[number,tokenHash]);return rows[0]||null;}
async function listPublicItems(orderId,connection=null){const[rows]=await db(connection).execute(`SELECT id,product_name_snapshot,variant_snapshot,quantity,unit_price,line_total FROM catalog_order_items WHERE catalog_order_id=? ORDER BY id`,[orderId]);return rows;}
function internalFilters(filters){const where=[],params=[];if(filters.q){const like=`%${filters.q}%`;where.push('(co.order_number LIKE ? OR co.contact_name LIKE ? OR co.contact_phone LIKE ? OR co.contact_whatsapp LIKE ?)');params.push(like,like,like,like);}if(filters.status){where.push('co.status=?');params.push(filters.status);}return{sql:where.length?`WHERE ${where.join(' AND ')}`:'',params};}
async function listOrders(filters,pagination){const f=internalFilters(filters);const[rows]=await getPool().execute(`SELECT co.id,co.order_number,co.status,co.contact_name,co.contact_phone,co.contact_whatsapp,co.total_amount,co.created_at,co.updated_at,co.reservation_expires_at,co.converted_sale_id,u.name assigned_user_name,COUNT(ci.id) item_count FROM catalog_orders co LEFT JOIN users u ON u.id=co.assigned_user_id LEFT JOIN catalog_order_items ci ON ci.catalog_order_id=co.id ${f.sql} GROUP BY co.id,co.order_number,co.status,co.contact_name,co.contact_phone,co.contact_whatsapp,co.total_amount,co.created_at,co.updated_at,co.reservation_expires_at,co.converted_sale_id,u.name ORDER BY FIELD(co.status,'NEW','WAITING_SERVICE','NEGOTIATING','CONFIRMED','EXPIRED','CONVERTED','CANCELLED'),co.created_at DESC,co.id DESC LIMIT ? OFFSET ?`,[...f.params,pagination.pageSize,pagination.offset]);const[count]=await getPool().execute(`SELECT COUNT(*) total FROM catalog_orders co ${f.sql}`,f.params);return{rows,total:Number(count[0].total)};}
async function findOrderById(id,connection=null){const[rows]=await db(connection).execute(`SELECT co.*,u.name assigned_user_name,cu.name customer_name,cf.name confirmed_by_name,cc.name cancelled_by_name FROM catalog_orders co LEFT JOIN users u ON u.id=co.assigned_user_id LEFT JOIN customers cu ON cu.id=co.customer_id LEFT JOIN users cf ON cf.id=co.confirmed_by_user_id LEFT JOIN users cc ON cc.id=co.cancelled_by_user_id WHERE co.id=? LIMIT 1`,[id]);return rows[0]||null;}
async function findOrderForUpdate(id,connection){const[rows]=await connection.execute('SELECT * FROM catalog_orders WHERE id=? FOR UPDATE',[id]);return rows[0]||null;}
async function listItemsForUpdate(orderId,connection){const[rows]=await connection.execute('SELECT * FROM catalog_order_items WHERE catalog_order_id=? ORDER BY product_sku_id,id FOR UPDATE',[orderId]);return rows;}
async function listItems(orderId,connection=null){const[rows]=await db(connection).execute(`SELECT ci.*,p.name current_product_name,c.name color_name,s.label size_label FROM catalog_order_items ci JOIN product_skus ps ON ps.id=ci.product_sku_id JOIN product_variants pv ON pv.id=ps.product_variant_id JOIN products p ON p.id=pv.product_id JOIN colors c ON c.id=pv.color_id JOIN sizes s ON s.id=ps.size_id WHERE ci.catalog_order_id=? ORDER BY ci.id`,[orderId]);return rows;}
async function findUser(id,connection){const[rows]=await connection.execute('SELECT id,name,is_active FROM users WHERE id=? LIMIT 1',[id]);return rows[0]||null;}
async function updateOperational(id,changes,connection){const cols=[],vals=[];if(Object.prototype.hasOwnProperty.call(changes,'status')){cols.push('status=?');vals.push(changes.status);}if(Object.prototype.hasOwnProperty.call(changes,'assignedUserId')){cols.push('assigned_user_id=?');vals.push(changes.assignedUserId);}if(Object.prototype.hasOwnProperty.call(changes,'internalNotes')){cols.push('internal_notes=?');vals.push(changes.internalNotes);}if(!cols.length)return;vals.push(id);await connection.execute(`UPDATE catalog_orders SET ${cols.join(',')} WHERE id=?`,vals);}
async function confirmOrder(id,data,userId,connection){await connection.execute(`UPDATE catalog_orders SET status='CONFIRMED',confirmed_at=CURRENT_TIMESTAMP(3),confirmed_by_user_id=?,reservation_expires_at=?,confirmation_operation_key=? WHERE id=?`,[userId,data.expiresAt,data.operationKey,id]);}
async function markExpired(id,connection){await connection.execute("UPDATE catalog_orders SET status='EXPIRED' WHERE id=? AND status='CONFIRMED' AND reservation_expires_at IS NOT NULL AND reservation_expires_at<=CURRENT_TIMESTAMP(3)",[id]);}
async function cancelOrder(id,userId,data,connection){await connection.execute(`UPDATE catalog_orders SET status='CANCELLED',cancelled_at=CURRENT_TIMESTAMP(3),cancelled_by_user_id=?,cancellation_reason=?,cancellation_operation_key=?,reservation_expires_at=NULL WHERE id=?`,[userId,data.reason,data.operationKey,id]);}
async function convertOrder(id,saleId,operationKey,connection){await connection.execute(`UPDATE catalog_orders SET status='CONVERTED',converted_sale_id=?,conversion_operation_key=?,reservation_expires_at=NULL WHERE id=?`,[saleId,operationKey,id]);}
async function findByConfirmationKey(key,connection=null){const[rows]=await db(connection).execute('SELECT * FROM catalog_orders WHERE confirmation_operation_key=? LIMIT 1',[key]);return rows[0]||null;}
async function findByConversionKey(key,connection=null){const[rows]=await db(connection).execute('SELECT * FROM catalog_orders WHERE conversion_operation_key=? LIMIT 1',[key]);return rows[0]||null;}
async function findByCancellationKey(key,connection=null){const[rows]=await db(connection).execute('SELECT * FROM catalog_orders WHERE cancellation_operation_key=? LIMIT 1',[key]);return rows[0]||null;}
async function createConvertedSale(order,actorId,temporaryNumber,connection){const[r]=await connection.execute(`INSERT INTO sales(sale_number,seller_user_id,updated_by_user_id,customer_id,status,subtotal,discount_amount,surcharge_amount,total_amount,notes) VALUES(?,?,?,?,'DRAFT',?,?,0.00,?,?)`,[temporaryNumber,actorId,actorId,order.customer_id||null,String(order.subtotal),'0.00',String(order.total_amount),`Pedido do catálogo ${order.order_number}. Contato: ${order.contact_name}.`]);return r.insertId;}
async function setConvertedSaleNumber(id,number,connection){await connection.execute('UPDATE sales SET sale_number=? WHERE id=?',[number,id]);}
async function createConvertedSaleItem(saleId,item,connection){const[r]=await connection.execute(`INSERT INTO sale_items(sale_id,product_sku_id,product_name_snapshot,sku_snapshot,variant_snapshot,quantity,original_unit_price,discount_amount,effective_unit_price,line_total,is_active) VALUES(?,?,?,?,?,?,?,0.00,?,?,1)`,[saleId,item.product_sku_id,item.product_name_snapshot,item.sku_snapshot,item.variant_snapshot,item.quantity,item.unit_price,item.unit_price,item.line_total]);return r.insertId;}
async function findConvertedSaleForUpdate(id,connection){const[rows]=await connection.execute('SELECT * FROM sales WHERE id=? FOR UPDATE',[id]);return rows[0]||null;}
async function cancelConvertedDraft(id,userId,reason,connection){await connection.execute(`UPDATE sales SET status='CANCELLED',cancelled_at=CURRENT_TIMESTAMP(3),cancelled_by_user_id=?,cancellation_reason=?,updated_by_user_id=? WHERE id=? AND status='DRAFT'`,[userId,reason,userId,id]);}
module.exports={expireAll,cancelConvertedDraft,createConvertedSale,createConvertedSaleItem,findConvertedSaleForUpdate,setConvertedSaleNumber,cancelOrder,confirmOrder,convertOrder,createItem,createOrder,ensureBalance,findByCancellationKey,findByConfirmationKey,findByConversionKey,findByPublicOperationKey,findOrderById,findOrderForUpdate,findPublicSkuForOrder,findPublicTracking,findUser,listItems,listItemsForUpdate,listOrders,listPublicItems,lockBalance,markExpired,setOrderNumber,setTotals,updateOperational};
