'use strict';

const { getPool } = require('../config/database');
function buildFilters(filters){const where=[];const params=[];if(filters.q){const like=`%${filters.q}%`;where.push('(p.document_number LIKE ? OR s.legal_name LIKE ? OR s.trade_name LIKE ?)');params.push(like,like,like);}if(filters.supplierId){where.push('p.supplier_id = ?');params.push(filters.supplierId);}if(filters.status){where.push('p.status = ?');params.push(filters.status);}if(filters.dateFrom){where.push('p.purchase_date >= ?');params.push(filters.dateFrom);}if(filters.dateTo){where.push('p.purchase_date <= ?');params.push(filters.dateTo);}return{sql:where.length?`WHERE ${where.join(' AND ')}`:'',params};}
async function listPurchases(filters,pagination){const built=buildFilters(filters);const db=getPool();const [rows]=await db.execute(`SELECT p.id,p.supplier_id,p.document_number,p.status,p.purchase_date,p.expected_date,p.received_at,p.subtotal,p.discount_amount,p.freight_amount,p.other_expenses_amount,p.total_amount,p.created_at,p.updated_at,s.legal_name AS supplier_legal_name,s.trade_name AS supplier_trade_name,COALESCE(SUM(CASE WHEN pi.is_active=1 THEN pi.quantity_ordered ELSE 0 END),0) AS total_ordered_units,COALESCE(SUM(CASE WHEN pi.is_active=1 THEN pi.quantity_received ELSE 0 END),0) AS total_received_units FROM purchases p JOIN suppliers s ON s.id=p.supplier_id LEFT JOIN purchase_items pi ON pi.purchase_id=p.id ${built.sql} GROUP BY p.id,s.legal_name,s.trade_name ORDER BY p.purchase_date DESC,p.id DESC LIMIT ? OFFSET ?`,[...built.params,pagination.pageSize,pagination.offset]);const [countRows]=await db.execute(`SELECT COUNT(*) AS total FROM purchases p JOIN suppliers s ON s.id=p.supplier_id ${built.sql}`,built.params);return{rows,total:Number(countRows[0].total)};}
async function findPurchaseById(id,connection=null,{forUpdate=false}={}){const db=connection||getPool();const [rows]=await db.execute(`SELECT p.*,s.legal_name AS supplier_legal_name,s.trade_name AS supplier_trade_name,s.is_active AS supplier_is_active FROM purchases p JOIN suppliers s ON s.id=p.supplier_id WHERE p.id = ?${forUpdate?' FOR UPDATE':''}`,[id]);return rows[0]||null;}
async function listPurchaseItems(purchaseId,connection=null){const db=connection||getPool();const [rows]=await db.execute(`SELECT pi.id,pi.purchase_id,pi.product_sku_id,pi.description_snapshot,pi.sku_snapshot,pi.quantity_ordered,pi.quantity_received,(pi.quantity_ordered-pi.quantity_received) AS quantity_pending,pi.unit_cost,pi.discount_amount,pi.line_total,pi.is_active,pi.cancelled_at,pi.cancelled_by_user_id,pi.created_at,pi.updated_at,ps.barcode,sz.label AS size_label,c.name AS color_name,pr.name AS product_name FROM purchase_items pi JOIN product_skus ps ON ps.id=pi.product_sku_id JOIN product_variants pv ON pv.id=ps.product_variant_id JOIN products pr ON pr.id=pv.product_id JOIN colors c ON c.id=pv.color_id JOIN sizes sz ON sz.id=ps.size_id WHERE pi.purchase_id=? ORDER BY pi.is_active DESC,pr.name,c.name,sz.sort_order,pi.id`,[purchaseId]);return rows;}
async function listPurchaseReceipts(purchaseId,connection=null){const db=connection||getPool();const [receipts]=await db.execute(`SELECT r.id,r.purchase_id,r.operation_key,r.notes,r.received_at,r.created_at,u.name AS received_by_name FROM purchase_receipts r JOIN users u ON u.id=r.received_by_user_id WHERE r.purchase_id=? ORDER BY r.received_at DESC,r.id DESC`,[purchaseId]);if(!receipts.length)return[];const ids=receipts.map(r=>r.id);const placeholders=ids.map(()=>'?').join(',');const [items]=await db.execute(`SELECT pri.purchase_receipt_id,pri.purchase_item_id,pri.quantity_received,pi.sku_snapshot,pi.description_snapshot FROM purchase_receipt_items pri JOIN purchase_items pi ON pi.id=pri.purchase_item_id WHERE pri.purchase_receipt_id IN (${placeholders}) ORDER BY pri.purchase_receipt_id,pri.purchase_item_id`,ids);return receipts.map(receipt=>({...receipt,items:items.filter(item=>String(item.purchase_receipt_id)===String(receipt.id))}));}
async function createPurchase(data,userId,connection){const [result]=await connection.execute(`INSERT INTO purchases (supplier_id,created_by_user_id,updated_by_user_id,document_number,status,purchase_date,expected_date,subtotal,discount_amount,freight_amount,other_expenses_amount,total_amount,notes) VALUES (?, ?, ?, ?, 'DRAFT', ?, ?, 0.00, ?, ?, ?, 0.00, ?)`,[data.supplierId,userId,userId,data.documentNumber,data.purchaseDate,data.expectedDate,data.discountAmount,data.freightAmount,data.otherExpensesAmount,data.notes]);return result.insertId;}
async function updatePurchase(id,data,userId,connection){const map={supplierId:'supplier_id',documentNumber:'document_number',purchaseDate:'purchase_date',expectedDate:'expected_date',discountAmount:'discount_amount',freightAmount:'freight_amount',otherExpensesAmount:'other_expenses_amount',notes:'notes'};const columns=[];const values=[];for(const [key,column] of Object.entries(map)){if(Object.prototype.hasOwnProperty.call(data,key)){columns.push(`${column} = ?`);values.push(data[key]);}}if(!columns.length)return;columns.push('updated_by_user_id = ?');values.push(userId,id);await connection.execute(`UPDATE purchases SET ${columns.join(', ')} WHERE id = ?`,values);}
async function lookupSkuById(skuId,connection=null){const db=connection||getPool();const [rows]=await db.execute(`SELECT ps.id,ps.sku,ps.barcode,ps.cost_price,ps.is_active AS sku_is_active,pv.is_active AS variant_is_active,p.is_active AS product_is_active,p.name AS product_name,p.base_cost_price,c.name AS color_name,s.label AS size_label FROM product_skus ps JOIN product_variants pv ON pv.id=ps.product_variant_id JOIN products p ON p.id=pv.product_id JOIN colors c ON c.id=pv.color_id JOIN sizes s ON s.id=ps.size_id WHERE ps.id=?`,[skuId]);return rows[0]||null;}
async function lookupSkus(q){const like=`%${q}%`;const [rows]=await getPool().execute(`SELECT ps.id,ps.sku,ps.barcode,COALESCE(ps.cost_price,p.base_cost_price) AS effective_cost_price,p.name AS product_name,c.name AS color_name,s.label AS size_label,COALESCE(sb.quantity,0) AS stock_quantity FROM product_skus ps JOIN product_variants pv ON pv.id=ps.product_variant_id JOIN products p ON p.id=pv.product_id JOIN colors c ON c.id=pv.color_id JOIN sizes s ON s.id=ps.size_id LEFT JOIN stock_balances sb ON sb.product_sku_id=ps.id WHERE ps.is_active=1 AND pv.is_active=1 AND p.is_active=1 AND (ps.sku LIKE ? OR ps.barcode LIKE ? OR p.name LIKE ?) ORDER BY p.name,c.name,s.sort_order,ps.id LIMIT 15`,[like,like,like]);return rows;}
async function createPurchaseItem(purchaseId,data,snapshot,connection){const [result]=await connection.execute(`INSERT INTO purchase_items (purchase_id,product_sku_id,description_snapshot,sku_snapshot,quantity_ordered,quantity_received,unit_cost,discount_amount,line_total,is_active) VALUES (?, ?, ?, ?, ?, 0, ?, ?, ?, 1)`,[purchaseId,data.skuId,snapshot.description,snapshot.sku,data.quantityOrdered,data.unitCost,data.discountAmount,data.lineTotal]);return result.insertId;}
async function findActiveItemBySku(purchaseId,skuId,connection){const [rows]=await connection.execute('SELECT id FROM purchase_items WHERE purchase_id=? AND product_sku_id=? AND is_active=1 LIMIT 1',[purchaseId,skuId]);return rows[0]||null;}
async function findPurchaseItemForUpdate(purchaseId,itemId,connection){const [rows]=await connection.execute(`SELECT id,purchase_id,product_sku_id,quantity_ordered,quantity_received,unit_cost,discount_amount,line_total,is_active,sku_snapshot,description_snapshot FROM purchase_items WHERE id=? AND purchase_id=? FOR UPDATE`,[itemId,purchaseId]);return rows[0]||null;}
async function updatePurchaseItem(itemId,data,connection){await connection.execute(`UPDATE purchase_items SET quantity_ordered=?,unit_cost=?,discount_amount=?,line_total=? WHERE id=?`,[data.quantityOrdered,data.unitCost,data.discountAmount,data.lineTotal,itemId]);}
async function cancelPurchaseItem(itemId,userId,connection){await connection.execute(`UPDATE purchase_items SET is_active=0,cancelled_at=CURRENT_TIMESTAMP(3),cancelled_by_user_id=? WHERE id=?`,[userId,itemId]);}
async function getActiveSubtotal(purchaseId,connection){const [rows]=await connection.execute('SELECT COALESCE(SUM(line_total),0.00) AS subtotal FROM purchase_items WHERE purchase_id=? AND is_active=1',[purchaseId]);return String(rows[0].subtotal);}
async function setPurchaseTotals(purchaseId,subtotal,totalAmount,userId,connection){await connection.execute('UPDATE purchases SET subtotal=?,total_amount=?,updated_by_user_id=? WHERE id=?',[subtotal,totalAmount,userId,purchaseId]);}
async function countActiveItems(purchaseId,connection){const [rows]=await connection.execute('SELECT COUNT(*) AS total FROM purchase_items WHERE purchase_id=? AND is_active=1',[purchaseId]);return Number(rows[0].total);}
async function setPurchaseStatus(purchaseId,status,userId,connection,{cancellationReason=null}={}){if(status==='CANCELLED'){await connection.execute(`UPDATE purchases SET status='CANCELLED',cancelled_by_user_id=?,cancelled_at=CURRENT_TIMESTAMP(3),cancellation_reason=?,updated_by_user_id=? WHERE id=?`,[userId,cancellationReason,userId,purchaseId]);return;}if(status==='RECEIVED'){await connection.execute(`UPDATE purchases SET status='RECEIVED',received_at=CURRENT_TIMESTAMP(3),updated_by_user_id=? WHERE id=?`,[userId,purchaseId]);return;}await connection.execute('UPDATE purchases SET status=?,updated_by_user_id=? WHERE id=?',[status,userId,purchaseId]);}
async function createReceipt(purchaseId,userId,operationKey,notes,connection){const [result]=await connection.execute(`INSERT INTO purchase_receipts (purchase_id,received_by_user_id,operation_key,notes) VALUES (?, ?, ?, ?)`,[purchaseId,userId,operationKey,notes]);return result.insertId;}
async function createReceiptItem(receiptId,purchaseItemId,quantity,connection){await connection.execute(`INSERT INTO purchase_receipt_items (purchase_receipt_id,purchase_item_id,quantity_received) VALUES (?, ?, ?)`,[receiptId,purchaseItemId,quantity]);}
async function incrementQuantityReceived(itemId,quantity,connection){await connection.execute('UPDATE purchase_items SET quantity_received=quantity_received+? WHERE id=?',[quantity,itemId]);}
async function remainingPurchaseUnits(purchaseId,connection){const [rows]=await connection.execute(`SELECT COALESCE(SUM(quantity_ordered-quantity_received),0) AS remaining FROM purchase_items WHERE purchase_id=? AND is_active=1`,[purchaseId]);return Number(rows[0].remaining);}
async function findReceiptByOperationKey(operationKey,connection=null){const db=connection||getPool();const [rows]=await db.execute('SELECT id,purchase_id,received_by_user_id,operation_key,notes,received_at,created_at FROM purchase_receipts WHERE operation_key=?',[operationKey]);if(!rows[0])return null;const [items]=await db.execute('SELECT purchase_item_id,quantity_received FROM purchase_receipt_items WHERE purchase_receipt_id=? ORDER BY purchase_item_id',[rows[0].id]);return{...rows[0],items};}
async function getReceiptById(receiptId,connection=null){const db=connection||getPool();const [rows]=await db.execute('SELECT id,purchase_id,received_by_user_id,operation_key,notes,received_at,created_at FROM purchase_receipts WHERE id=?',[receiptId]);if(!rows[0])return null;const [items]=await db.execute('SELECT purchase_item_id,quantity_received FROM purchase_receipt_items WHERE purchase_receipt_id=? ORDER BY purchase_item_id',[receiptId]);return{...rows[0],items};}
module.exports={cancelPurchaseItem,countActiveItems,createPurchase,createPurchaseItem,createReceipt,createReceiptItem,findActiveItemBySku,findPurchaseById,findPurchaseItemForUpdate,findReceiptByOperationKey,getActiveSubtotal,getReceiptById,incrementQuantityReceived,listPurchaseItems,listPurchaseReceipts,listPurchases,lookupSkuById,lookupSkus,remainingPurchaseUnits,setPurchaseStatus,setPurchaseTotals,updatePurchase,updatePurchaseItem};
