'use strict';

const { getPool } = require('../config/database');
function db(connection){return connection||getPool();}
async function lookupSkus(q,connection=null){const like=`%${q}%`;const[rows]=await db(connection).execute(`SELECT ps.id,ps.sku,ps.barcode,ps.is_active AS sku_is_active,pv.id AS variant_id,pv.is_active AS variant_is_active,c.name AS color_name,s.label AS size_label,p.id AS product_id,p.name AS product_name,p.is_active AS product_is_active,COALESCE(ps.promotional_price,ps.sale_price,p.promotional_price,p.base_sale_price) AS current_price,COALESCE(sb.quantity,0) AS stock_quantity FROM product_skus ps JOIN product_variants pv ON pv.id=ps.product_variant_id JOIN products p ON p.id=pv.product_id JOIN colors c ON c.id=pv.color_id JOIN sizes s ON s.id=ps.size_id LEFT JOIN stock_balances sb ON sb.product_sku_id=ps.id WHERE (p.name LIKE ? OR ps.sku LIKE ? OR ps.barcode LIKE ? OR c.name LIKE ? OR s.label LIKE ?) AND p.is_active=1 AND pv.is_active=1 AND ps.is_active=1 ORDER BY p.name,c.name,s.sort_order,s.label LIMIT 20`,[like,like,like,like,like]);return rows;}
async function findSkuById(id,connection=null){const[rows]=await db(connection).execute(`SELECT ps.id,ps.sku,ps.barcode,ps.is_active AS sku_is_active,pv.id AS variant_id,pv.variant_name,pv.is_active AS variant_is_active,c.name AS color_name,s.label AS size_label,p.id AS product_id,p.name AS product_name,p.is_active AS product_is_active,COALESCE(ps.promotional_price,ps.sale_price,p.promotional_price,p.base_sale_price) AS current_price,COALESCE(sb.quantity,0) AS stock_quantity FROM product_skus ps JOIN product_variants pv ON pv.id=ps.product_variant_id JOIN products p ON p.id=pv.product_id JOIN colors c ON c.id=pv.color_id JOIN sizes s ON s.id=ps.size_id LEFT JOIN stock_balances sb ON sb.product_sku_id=ps.id WHERE ps.id=? LIMIT 1`,[id]);return rows[0]||null;}
async function findCustomerById(id,connection=null){const[rows]=await db(connection).execute('SELECT id,name,is_active FROM customers WHERE id=? LIMIT 1',[id]);return rows[0]||null;}
function buildFilters(filters={}){const where=[],params=[];if(filters.q){const like=`%${filters.q}%`;where.push('(sa.sale_number LIKE ? OR c.name LIKE ? OR u.name LIKE ?)');params.push(like,like,like);}if(filters.customerId){where.push('sa.customer_id=?');params.push(filters.customerId);}if(filters.status){where.push('sa.status=?');params.push(filters.status);}if(filters.dateFrom){where.push('COALESCE(sa.sold_at,sa.created_at)>=?');params.push(`${filters.dateFrom} 00:00:00`);}if(filters.dateTo){where.push('COALESCE(sa.sold_at,sa.created_at)<DATE_ADD(?,INTERVAL 1 DAY)');params.push(`${filters.dateTo} 00:00:00`);}return{sql:where.length?`WHERE ${where.join(' AND ')}`:'',params};}
async function listSales(filters,pagination){const built=buildFilters(filters);const[rows]=await getPool().execute(`SELECT sa.id,sa.sale_number,sa.customer_id,sa.seller_user_id,sa.status,sa.subtotal,sa.discount_amount,sa.surcharge_amount,sa.total_amount,sa.sold_at,sa.cancelled_at,sa.created_at,c.name AS customer_name,u.name AS seller_name,COUNT(si.id) AS item_count FROM sales sa JOIN users u ON u.id=sa.seller_user_id LEFT JOIN customers c ON c.id=sa.customer_id LEFT JOIN sale_items si ON si.sale_id=sa.id AND si.is_active=1 ${built.sql} GROUP BY sa.id,sa.sale_number,sa.customer_id,sa.seller_user_id,sa.status,sa.subtotal,sa.discount_amount,sa.surcharge_amount,sa.total_amount,sa.sold_at,sa.cancelled_at,sa.created_at,c.name,u.name ORDER BY sa.created_at DESC,sa.id DESC LIMIT ? OFFSET ?`,[...built.params,pagination.pageSize,pagination.offset]);const[countRows]=await getPool().execute(`SELECT COUNT(*) AS total FROM sales sa JOIN users u ON u.id=sa.seller_user_id LEFT JOIN customers c ON c.id=sa.customer_id ${built.sql}`,built.params);return{rows,total:Number(countRows[0].total)};}
async function findSaleById(id,connection=null){const[rows]=await db(connection).execute(`SELECT sa.*,c.name AS customer_name,c.is_active AS customer_is_active,seller.name AS seller_name,updater.name AS updated_by_name,completer.name AS completed_by_name FROM sales sa JOIN users seller ON seller.id=sa.seller_user_id LEFT JOIN users updater ON updater.id=sa.updated_by_user_id LEFT JOIN users completer ON completer.id=sa.completed_by_user_id LEFT JOIN customers c ON c.id=sa.customer_id WHERE sa.id=? LIMIT 1`,[id]);return rows[0]||null;}
async function findSaleForUpdate(id,connection){const[rows]=await connection.execute('SELECT * FROM sales WHERE id=? FOR UPDATE',[id]);return rows[0]||null;}
async function createSale(data,actorId,temporaryNumber,connection){const[result]=await connection.execute(`INSERT INTO sales (sale_number,seller_user_id,updated_by_user_id,customer_id,status,subtotal,discount_amount,surcharge_amount,total_amount,notes) VALUES (?,?,?,?,'DRAFT',0.00,0.00,0.00,0.00,?)`,[temporaryNumber,actorId,actorId,data.customerId,data.notes]);return result.insertId;}
async function setSaleNumber(id,saleNumber,connection){await connection.execute('UPDATE sales SET sale_number=? WHERE id=?',[saleNumber,id]);}
async function updateDraft(id,data,actorId,connection){const columns=[],values=[];if(Object.prototype.hasOwnProperty.call(data,'customerId')){columns.push('customer_id=?');values.push(data.customerId);}if(Object.prototype.hasOwnProperty.call(data,'notes')){columns.push('notes=?');values.push(data.notes);}if(!columns.length)return;columns.push('updated_by_user_id=?');values.push(actorId,id);await connection.execute(`UPDATE sales SET ${columns.join(',')} WHERE id=?`,values);}
async function setPricing(id,pricing,actorId,connection){await connection.execute('UPDATE sales SET discount_amount=?,surcharge_amount=?,updated_by_user_id=? WHERE id=?',[pricing.discountAmount,pricing.surchargeAmount,actorId,id]);}
async function setTotals(id,subtotal,totalAmount,actorId,connection){await connection.execute('UPDATE sales SET subtotal=?,total_amount=?,updated_by_user_id=? WHERE id=?',[subtotal,totalAmount,actorId,id]);}
async function listSaleItems(saleId,connection=null){const[rows]=await db(connection).execute(`SELECT si.*,p.name AS current_product_name,c.name AS color_name,s.label AS size_label FROM sale_items si JOIN product_skus ps ON ps.id=si.product_sku_id JOIN product_variants pv ON pv.id=ps.product_variant_id JOIN products p ON p.id=pv.product_id JOIN colors c ON c.id=pv.color_id JOIN sizes s ON s.id=ps.size_id WHERE si.sale_id=? ORDER BY si.is_active DESC,si.id`,[saleId]);return rows;}
async function findActiveItemBySku(saleId,skuId,connection){const[rows]=await connection.execute('SELECT * FROM sale_items WHERE sale_id=? AND product_sku_id=? AND is_active=1 LIMIT 1',[saleId,skuId]);return rows[0]||null;}
async function findSaleItemForUpdate(saleId,itemId,connection){const[rows]=await connection.execute('SELECT * FROM sale_items WHERE id=? AND sale_id=? FOR UPDATE',[itemId,saleId]);return rows[0]||null;}
async function createSaleItem(saleId,item,sku,line,connection){const[result]=await connection.execute(`INSERT INTO sale_items (sale_id,product_sku_id,product_name_snapshot,sku_snapshot,variant_snapshot,quantity,original_unit_price,discount_amount,effective_unit_price,line_total,is_active) VALUES (?,?,?,?,?,?,?,?,?,?,1)`,[saleId,item.skuId,sku.product_name,sku.sku,`${sku.color_name} · ${sku.size_label}`,item.quantity,line.originalUnitPrice,line.discountAmount,line.effectiveUnitPrice,line.lineTotal]);return result.insertId;}
async function updateSaleItem(itemId,quantity,line,connection){await connection.execute('UPDATE sale_items SET quantity=?,discount_amount=?,effective_unit_price=?,line_total=? WHERE id=?',[quantity,line.discountAmount,line.effectiveUnitPrice,line.lineTotal,itemId]);}
async function cancelSaleItem(itemId,actorId,connection){await connection.execute('UPDATE sale_items SET is_active=0,cancelled_at=CURRENT_TIMESTAMP(3),cancelled_by_user_id=? WHERE id=?',[actorId,itemId]);}
async function activeSubtotal(saleId,connection){const[rows]=await connection.execute('SELECT COALESCE(SUM(line_total),0.00) AS subtotal FROM sale_items WHERE sale_id=? AND is_active=1',[saleId]);return String(rows[0].subtotal);}
async function countActiveItems(saleId,connection){const[rows]=await connection.execute('SELECT COUNT(*) AS total FROM sale_items WHERE sale_id=? AND is_active=1',[saleId]);return Number(rows[0].total);}
async function findByCompletionKey(operationKey,connection=null){const[rows]=await db(connection).execute('SELECT * FROM sales WHERE completion_operation_key=? LIMIT 1',[operationKey]);return rows[0]||null;}
async function findByCancellationKey(operationKey,connection=null){const[rows]=await db(connection).execute('SELECT * FROM sales WHERE cancellation_operation_key=? LIMIT 1',[operationKey]);return rows[0]||null;}
async function completeSale(id,actorId,operationKey,connection){await connection.execute(`UPDATE sales SET status='COMPLETED',sold_at=CURRENT_TIMESTAMP(3),completed_by_user_id=?,updated_by_user_id=?,completion_operation_key=? WHERE id=?`,[actorId,actorId,operationKey,id]);}
async function cancelSale(id,actorId,reason,operationKey,connection){await connection.execute(`UPDATE sales SET status='CANCELLED',cancelled_at=CURRENT_TIMESTAMP(3),cancelled_by_user_id=?,cancellation_reason=?,cancellation_operation_key=?,updated_by_user_id=? WHERE id=?`,[actorId,reason,operationKey,actorId,id]);}
async function hasFinancialLinks(saleId,connection){const[allocations]=await connection.execute('SELECT id FROM sale_payment_allocations WHERE sale_id=? LIMIT 1',[saleId]);const[receivables]=await connection.execute("SELECT id FROM receivables WHERE sale_id=? AND status<>'CANCELLED' LIMIT 1",[saleId]);return Boolean(allocations[0]||receivables[0]);}
module.exports={activeSubtotal,cancelSale,cancelSaleItem,completeSale,countActiveItems,createSale,createSaleItem,findActiveItemBySku,findByCancellationKey,findByCompletionKey,findCustomerById,findSaleById,findSaleForUpdate,findSaleItemForUpdate,findSkuById,hasFinancialLinks,listSaleItems,listSales,lookupSkus,setPricing,setSaleNumber,setTotals,updateDraft,updateSaleItem};
