'use strict';
const { getPool } = require('../config/database');
function db(connection){return connection||getPool();}
async function expireForSku(skuId,connection){await connection.execute("UPDATE stock_reservations SET status='EXPIRED' WHERE product_sku_id=? AND status='ACTIVE' AND expires_at IS NOT NULL AND expires_at<=CURRENT_TIMESTAMP(3)",[skuId]);}
async function expireForOrder(orderId,connection){await connection.execute("UPDATE stock_reservations SET status='EXPIRED' WHERE catalog_order_id=? AND status='ACTIVE' AND expires_at IS NOT NULL AND expires_at<=CURRENT_TIMESTAMP(3)",[orderId]);}
async function activeReservedForSku(skuId,connection=null){const[rows]=await db(connection).execute("SELECT COALESCE(SUM(quantity),0) total FROM stock_reservations WHERE product_sku_id=? AND status='ACTIVE' AND (expires_at IS NULL OR expires_at>CURRENT_TIMESTAMP(3))",[skuId]);return Number(rows[0].total||0);}
async function activeReservedForOrderSku(orderId,skuId,connection=null){const[rows]=await db(connection).execute("SELECT COALESCE(SUM(quantity),0) total FROM stock_reservations WHERE catalog_order_id=? AND product_sku_id=? AND status='ACTIVE' AND (expires_at IS NULL OR expires_at>CURRENT_TIMESTAMP(3))",[orderId,skuId]);return Number(rows[0].total||0);}
async function createReservation(data,connection){const[r]=await connection.execute(`INSERT INTO stock_reservations(catalog_order_id,catalog_order_item_id,product_sku_id,quantity,status,operation_key,expires_at,created_by_user_id) VALUES(?,?,?,?,'ACTIVE',?,?,?)`,[data.catalogOrderId,data.catalogOrderItemId,data.skuId,data.quantity,data.operationKey,data.expiresAt,data.userId]);return r.insertId;}
async function listForOrder(orderId,connection=null){const[rows]=await db(connection).execute(`SELECT sr.id,sr.catalog_order_item_id,sr.product_sku_id,sr.quantity,sr.status,sr.expires_at,sr.created_at,sr.released_at,sr.consumed_at,u.name created_by_name FROM stock_reservations sr JOIN users u ON u.id=sr.created_by_user_id WHERE sr.catalog_order_id=? ORDER BY sr.id`,[orderId]);return rows;}
async function releaseActiveForOrder(orderId,userId,reason,connection){const[r]=await connection.execute("UPDATE stock_reservations SET status='RELEASED',released_by_user_id=?,release_reason=?,released_at=CURRENT_TIMESTAMP(3) WHERE catalog_order_id=? AND status='ACTIVE'",[userId,reason,orderId]);return r.affectedRows;}
async function consumeActiveForOrder(orderId,userId,connection){const[r]=await connection.execute("UPDATE stock_reservations SET status='CONSUMED',consumed_by_user_id=?,consumed_at=CURRENT_TIMESTAMP(3) WHERE catalog_order_id=? AND status='ACTIVE'",[userId,orderId]);return r.affectedRows;}
async function makeNonExpiring(orderId,connection){await connection.execute("UPDATE stock_reservations SET expires_at=NULL WHERE catalog_order_id=? AND status='ACTIVE'",[orderId]);}
async function hasActiveForOrder(orderId,connection=null){const[rows]=await db(connection).execute("SELECT id FROM stock_reservations WHERE catalog_order_id=? AND status='ACTIVE' AND (expires_at IS NULL OR expires_at>CURRENT_TIMESTAMP(3)) LIMIT 1",[orderId]);return Boolean(rows[0]);}
module.exports={activeReservedForOrderSku,activeReservedForSku,consumeActiveForOrder,createReservation,expireForOrder,expireForSku,hasActiveForOrder,listForOrder,makeNonExpiring,releaseActiveForOrder};
