'use strict';

const crypto = require('crypto');
const { HttpError } = require('./httpError');
function text(value,max,label,{required=false}={}){const n=String(value??'').trim().replace(/\s+/g,' ');if(required&&!n)throw new HttpError(400,'FIELD_REQUIRED',`${label} é obrigatório.`);if(n.length>max)throw new HttpError(400,'FIELD_TOO_LONG',`${label} excede ${max} caracteres.`);return n||null;}
function phone(value,label){const raw=String(value??'').trim();if(!raw)return null;const digits=raw.replace(/\D/g,'');if(digits.length<8||digits.length>15)throw new HttpError(400,'INVALID_PHONE',`${label} inválido.`);return digits;}
function email(value){const n=String(value??'').trim().toLowerCase();if(!n)return null;if(n.length>190||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(n))throw new HttpError(400,'INVALID_EMAIL','E-mail inválido.');return n;}
function positiveInt(value,label,max=Number.MAX_SAFE_INTEGER){const n=Number(value);if(!Number.isSafeInteger(n)||n<1||n>max)throw new HttpError(400,'INVALID_NUMBER',`${label} inválido.`);return n;}
function operationKey(value){const n=String(value??'').trim();if(!/^[A-Za-z0-9._:-]{16,64}$/.test(n))throw new HttpError(400,'INVALID_OPERATION_KEY','Chave de operação inválida.');return n;}
function trackingToken(value){const n=String(value??'').trim();if(!/^[A-Za-z0-9._:-]{24,160}$/.test(n))throw new HttpError(400,'INVALID_TRACKING_TOKEN','Token de acompanhamento inválido.');return n;}
function hashToken(value){return crypto.createHash('sha256').update(String(value),'utf8').digest('hex');}
function cents(value,label='Valor'){const n=String(value??'').trim().replace(',','.');if(!/^\d+(\.\d{1,2})?$/.test(n))throw new HttpError(400,'INVALID_MONEY',`${label} inválido.`);const[whole,decimal='']=n.split('.');const result=Number(whole)*100+Number(decimal.padEnd(2,'0'));if(!Number.isSafeInteger(result)||result<0)throw new HttpError(400,'INVALID_MONEY',`${label} inválido.`);return result;}
function fromCents(value){return `${Math.floor(value/100)}.${String(value%100).padStart(2,'0')}`;}function lineTotal(unitPrice,quantity){return fromCents(cents(unitPrice,'Preço')*positiveInt(quantity,'Quantidade',99));}
function normalizePublicOrder(input={}){if(String(input.website??'').trim())throw new HttpError(400,'INVALID_ORDER','Não foi possível enviar o pedido.');const contactName=text(input.contactName,180,'Nome',{required:true}),contactPhone=phone(input.contactPhone,'Telefone'),contactWhatsapp=phone(input.contactWhatsapp,'WhatsApp'),contactEmail=email(input.contactEmail);if(!contactPhone&&!contactWhatsapp&&!contactEmail)throw new HttpError(400,'CONTACT_REQUIRED','Informe telefone, WhatsApp ou e-mail.');if(!Array.isArray(input.items)||input.items.length<1||input.items.length>20)throw new HttpError(400,'INVALID_ORDER_ITEMS','O pedido deve possuir de 1 a 20 itens.');const seen=new Set();const items=input.items.map(item=>{const skuId=positiveInt(item?.skuId,'SKU'),quantity=positiveInt(item?.quantity,'Quantidade',10);if(seen.has(skuId))throw new HttpError(400,'DUPLICATE_ORDER_SKU','O mesmo tamanho não pode aparecer duas vezes no pedido.');seen.add(skuId);return{skuId,quantity};}).sort((a,b)=>a.skuId-b.skuId);return{contactName,contactPhone,contactWhatsapp,contactEmail,notes:text(input.notes,500,'Observações'),items,operationKey:operationKey(input.operationKey),trackingToken:trackingToken(input.trackingToken)};}
function requestHash(order){const payload={contactName:order.contactName,contactPhone:order.contactPhone,contactWhatsapp:order.contactWhatsapp,contactEmail:order.contactEmail,notes:order.notes,items:order.items.map(({skuId,quantity})=>({skuId,quantity}))};return crypto.createHash('sha256').update(JSON.stringify(payload),'utf8').digest('hex');}
function normalizeTracking(input={}){const number=String(input.orderNumber??'').trim().toUpperCase();if(!/^C\d{8}-\d{8}$/.test(number))throw new HttpError(400,'INVALID_ORDER_NUMBER','Número do pedido inválido.');return{orderNumber:number,tokenHash:hashToken(trackingToken(input.trackingToken))};}
function normalizeReservation(input={}){const hours=input.reservationHours===undefined?48:positiveInt(input.reservationHours,'Prazo da reserva',168);return{operationKey:operationKey(input.operationKey),reservationHours:hours};}
function normalizeCancellation(input={}){return{operationKey:operationKey(input.operationKey),reason:text(input.reason,500,'Motivo',{required:true})};}function normalizeConversion(input={}){return{operationKey:operationKey(input.operationKey)};}
function reservationExpiry(hours,now=new Date()){return new Date(now.getTime()+positiveInt(hours,'Prazo da reserva',168)*3600000);}function availablePhysical(physical,reserved,ownReserved=0){const p=Math.max(0,Number(physical)||0),r=Math.max(0,Number(reserved)||0),own=Math.max(0,Number(ownReserved)||0);return Math.max(0,p-Math.max(0,r-own));}
const TRANSITIONS={NEW:new Set(['WAITING_SERVICE','CANCELLED']),WAITING_SERVICE:new Set(['NEGOTIATING','CANCELLED']),NEGOTIATING:new Set(['WAITING_SERVICE','CANCELLED']),EXPIRED:new Set(['NEGOTIATING','CANCELLED']),CONFIRMED:new Set(['CANCELLED']),CONVERTED:new Set([]),CANCELLED:new Set([])};
function assertTransition(current,next){const c=String(current||'').toUpperCase(),n=String(next||'').toUpperCase();if(!TRANSITIONS[c]?.has(n))throw new HttpError(409,'INVALID_ORDER_TRANSITION',`Transição ${c||'?'} → ${n||'?'} não permitida.`);return n;}
function normalizeInternalPatch(input={}){const out={};if(Object.prototype.hasOwnProperty.call(input,'status')){const status=String(input.status??'').trim().toUpperCase();if(!['WAITING_SERVICE','NEGOTIATING'].includes(status))throw new HttpError(400,'INVALID_ORDER_STATUS','Status operacional inválido.');out.status=status;}if(Object.prototype.hasOwnProperty.call(input,'assignedUserId'))out.assignedUserId=input.assignedUserId===null||input.assignedUserId===''?null:positiveInt(input.assignedUserId,'Responsável');if(Object.prototype.hasOwnProperty.call(input,'internalNotes'))out.internalNotes=text(input.internalNotes,500,'Observações internas');if(!Object.keys(out).length)throw new HttpError(400,'NO_CHANGES','Nenhuma alteração válida foi informada.');return out;}
module.exports={assertTransition,availablePhysical,cents,fromCents,hashToken,lineTotal,normalizeCancellation,normalizeConversion,normalizeInternalPatch,normalizePublicOrder,normalizeReservation,normalizeTracking,operationKey,positiveInt,requestHash,reservationExpiry};
