'use strict';

const crypto = require('crypto');
const { HttpError } = require('./httpError');

function text(value) { const normalized = String(value ?? '').trim(); return normalized || null; }
function parsePositiveId(value, label = 'Registro') { const id = Number(value); if (!Number.isSafeInteger(id) || id < 1) throw new HttpError(400, 'INVALID_ID', `${label} inválido.`); return id; }
function parseQuantity(value) { const quantity = Number(value); if (!Number.isSafeInteger(quantity) || quantity < 1 || quantity > 999) throw new HttpError(400, 'INVALID_SALE_QUANTITY', 'Quantidade deve ficar entre 1 e 999.'); return quantity; }
function moneyToCents(value, label, { nullable = false } = {}) { if ((value === null || value === undefined || value === '') && nullable) return null; const normalized = String(value ?? '').trim().replace(',', '.'); if (!/^\d{1,13}(?:\.\d{1,2})?$/.test(normalized)) throw new HttpError(400, 'INVALID_MONEY', `${label} inválido.`); const [whole, fraction = ''] = normalized.split('.'); const cents = Number(whole) * 100 + Number((fraction + '00').slice(0, 2)); if (!Number.isSafeInteger(cents) || cents < 0) throw new HttpError(400, 'INVALID_MONEY', `${label} inválido.`); return cents; }
function centsToMoney(cents) { if (!Number.isSafeInteger(cents) || cents < 0) throw new Error('Valor monetário interno inválido.'); return `${Math.floor(cents / 100)}.${String(cents % 100).padStart(2, '0')}`; }
function calculateSaleLine(originalUnitPrice, quantity, discountAmount = '0.00') { const unitCents = moneyToCents(originalUnitPrice, 'Preço unitário'); const qty = parseQuantity(quantity); const discountCents = moneyToCents(discountAmount, 'Desconto do item'); const grossCents = unitCents * qty; if (discountCents > grossCents) throw new HttpError(400, 'ITEM_DISCOUNT_EXCEEDS_TOTAL', 'Desconto do item não pode superar o total bruto da linha.'); const lineCents = grossCents - discountCents; return { originalUnitPrice: centsToMoney(unitCents), discountAmount: centsToMoney(discountCents), effectiveUnitPrice: centsToMoney(Math.round(lineCents / qty)), lineTotal: centsToMoney(lineCents) }; }
function calculateSaleTotal(subtotal, discountAmount = '0.00', surchargeAmount = '0.00') { const subtotalCents = moneyToCents(subtotal, 'Subtotal'); const discountCents = moneyToCents(discountAmount, 'Desconto geral'); const surchargeCents = moneyToCents(surchargeAmount, 'Acréscimo'); if (discountCents > subtotalCents + surchargeCents) throw new HttpError(400, 'SALE_DISCOUNT_EXCEEDS_TOTAL', 'Desconto geral não pode tornar o total da venda negativo.'); return centsToMoney(subtotalCents - discountCents + surchargeCents); }
function normalizeNotes(value) { const notes = text(value); if (notes && notes.length > 2000) throw new HttpError(400, 'INVALID_SALE_NOTES', 'Observações excedem 2000 caracteres.'); return notes; }
function normalizeSaleHeader(input, { partial = false } = {}) { const out = {}; const has = (key) => Object.prototype.hasOwnProperty.call(input || {}, key); if (!partial || has('customerId')) out.customerId = input?.customerId === null || input?.customerId === undefined || input?.customerId === '' ? null : parsePositiveId(input.customerId, 'Cliente'); if (!partial || has('notes')) out.notes = normalizeNotes(input?.notes); return out; }
function normalizeSaleItem(input) { return { skuId: parsePositiveId(input?.skuId, 'SKU'), quantity: parseQuantity(input?.quantity) }; }
function normalizePricing(input) { return { discountAmount: centsToMoney(moneyToCents(input?.discountAmount ?? '0.00', 'Desconto geral')), surchargeAmount: centsToMoney(moneyToCents(input?.surchargeAmount ?? '0.00', 'Acréscimo')) }; }
function normalizeItemDiscount(input) { return centsToMoney(moneyToCents(input?.discountAmount ?? '0.00', 'Desconto do item')); }
function normalizeOperationKey(value) { const key = String(value ?? '').trim(); if (key.length < 16 || key.length > 64 || !/^[A-Za-z0-9._:-]+$/.test(key)) throw new HttpError(400, 'INVALID_OPERATION_KEY', 'Chave da operação deve possuir de 16 a 64 caracteres seguros.'); return key; }
function stockOperationKey(operationKey, saleItemId, typeCode) { return crypto.createHash('sha256').update(`${typeCode}:${operationKey}:${saleItemId}`).digest('hex'); }
function normalizeCancellationReason(value) { const reason = String(value ?? '').trim(); if (reason.length < 5 || reason.length > 500) throw new HttpError(400, 'INVALID_CANCELLATION_REASON', 'Motivo do cancelamento deve possuir entre 5 e 500 caracteres.'); return reason; }
function normalizeSaleStatusFilter(value) { const status = String(value ?? '').trim().toUpperCase(); const allowed = new Set(['', 'DRAFT', 'COMPLETED', 'CANCELLED', 'PARTIALLY_RETURNED', 'RETURNED']); if (!allowed.has(status)) throw new HttpError(400, 'INVALID_SALE_STATUS', 'Status de venda inválido.'); return status || null; }

module.exports = { calculateSaleLine, calculateSaleTotal, centsToMoney, moneyToCents, normalizeCancellationReason, normalizeItemDiscount, normalizeOperationKey, normalizePricing, normalizeSaleHeader, normalizeSaleItem, normalizeSaleStatusFilter, parsePositiveId, stockOperationKey };
